package shufersal

type ShufersalResponse struct {
	Results []struct {
		Code        string      `json:"code"`
		Name        string      `json:"name"`
		URL         string      `json:"url"`
		Description string      `json:"description"`
		Purchasable interface{} `json:"purchasable"`
		Stock       struct {
			StockLevelStatus struct {
				Code string `json:"code"`
				Type string `json:"type"`
			} `json:"stockLevelStatus"`
			StockLevel          interface{} `json:"stockLevel"`
			StockThreshold      interface{} `json:"stockThreshold"`
			Available           interface{} `json:"available"`
			Reserved            interface{} `json:"reserved"`
			InvMethod           interface{} `json:"invMethod"`
			InventoryManagement interface{} `json:"inventoryManagement"`
			InventoryOnTheWay   interface{} `json:"inventoryOnTheWay"`
			MinimalThreshold1   interface{} `json:"minimalThreshold1"`
			MinimalThreshold2   interface{} `json:"minimalThreshold2"`
			Warehouse           interface{} `json:"warehouse"`
			ProductCode         interface{} `json:"productCode"`
		} `json:"stock"`
		FutureStocks       interface{} `json:"futureStocks"`
		AvailableForPickup bool        `json:"availableForPickup"`
		AverageRating      interface{} `json:"averageRating"`
		NumberOfReviews    int         `json:"numberOfReviews"`
		Summary            interface{} `json:"summary"`
		Manufacturer       string      `json:"manufacturer"`
		VariantType        interface{} `json:"variantType"`
		Price              struct {
			CurrencyIso    string      `json:"currencyIso"`
			Value          float64     `json:"value"`
			PriceType      string      `json:"priceType"`
			FormattedValue string      `json:"formattedValue"`
			MinQuantity    interface{} `json:"minQuantity"`
			MaxQuantity    interface{} `json:"maxQuantity"`
		} `json:"price"`
		BaseProduct string `json:"baseProduct"`
		Images      []struct {
			ImageType    string      `json:"imageType"`
			Format       string      `json:"format"`
			URL          string      `json:"url"`
			AltText      interface{} `json:"altText"`
			GalleryIndex interface{} `json:"galleryIndex"`
			Width        interface{} `json:"width"`
			Code         interface{} `json:"code"`
		} `json:"images"`
		Categories          interface{} `json:"categories"`
		Reviews             interface{} `json:"reviews"`
		Classifications     interface{} `json:"classifications"`
		PotentialPromotions interface{} `json:"potentialPromotions"`
		VariantOptions      interface{} `json:"variantOptions"`
		BaseOptions         interface{} `json:"baseOptions"`
		VolumePricesFlag    bool        `json:"volumePricesFlag"`
		VolumePrices        interface{} `json:"volumePrices"`
		ProductReferences   interface{} `json:"productReferences"`
		VariantMatrix       interface{} `json:"variantMatrix"`
		PriceRange          struct {
			MinPrice interface{} `json:"minPrice"`
			MaxPrice interface{} `json:"maxPrice"`
		} `json:"priceRange"`
		FirstCategoryNameList interface{} `json:"firstCategoryNameList"`
		Multidimensional      interface{} `json:"multidimensional"`
		Configurable          interface{} `json:"configurable"`
		Keywords              interface{} `json:"keywords"`
		Genders               interface{} `json:"genders"`
		Sku                   string      `json:"sku"`
		CommercialDepartment  interface{} `json:"commercialDepartment"`
		Brand                 struct {
			Code interface{} `json:"code"`
			Name string      `json:"name"`
		} `json:"brand"`
		BrandName             string      `json:"brandName"`
		DeliveryItem          interface{} `json:"deliveryItem"`
		AssociatedDeiveryItem interface{} `json:"associatedDeiveryItem"`
		InventoryManagement   interface{} `json:"inventoryManagement"`
		SellingMethod         struct {
			Code string `json:"code"`
			Type string `json:"type"`
		} `json:"sellingMethod"`
		GroupingCode           interface{} `json:"groupingCode"`
		Country                interface{} `json:"country"`
		ManufacturerInfo       interface{} `json:"manufacturerInfo"`
		PrivateLabel           bool        `json:"privateLabel"`
		NewProduct             bool        `json:"newProduct"`
		ShowOnSite             interface{} `json:"showOnSite"`
		ShowOnMobile           interface{} `json:"showOnMobile"`
		Searchable             interface{} `json:"searchable"`
		Indexable              interface{} `json:"indexable"`
		PackagingType          interface{} `json:"packagingType"`
		SourceOfSupply         string      `json:"sourceOfSupply"`
		ProductType            interface{} `json:"productType"`
		AdultsOnly             bool        `json:"adultsOnly"`
		GiftProduct            interface{} `json:"giftProduct"`
		ProductSet             interface{} `json:"productSet"`
		MinOrderWeight         interface{} `json:"minOrderWeight"`
		MaxOrderWeight         float64     `json:"maxOrderWeight"`
		MinOrderQuantity       interface{} `json:"minOrderQuantity"`
		MaxOrderQuantity       int         `json:"maxOrderQuantity"`
		Food                   bool        `json:"food"`
		IgnoreERPCategory      interface{} `json:"ignoreERPCategory"`
		StockReservationMethod interface{} `json:"stockReservationMethod"`
		Ean                    interface{} `json:"ean"`
		PopularityRanking      interface{} `json:"popularityRanking"`
		PricePerUnit           struct {
			CurrencyIso    string      `json:"currencyIso"`
			Value          float64     `json:"value"`
			PriceType      string      `json:"priceType"`
			FormattedValue string      `json:"formattedValue"`
			MinQuantity    interface{} `json:"minQuantity"`
			MaxQuantity    interface{} `json:"maxQuantity"`
		} `json:"pricePerUnit"`
		CategoryPrice struct {
			CurrencyIso    string      `json:"currencyIso"`
			Value          float64     `json:"value"`
			PriceType      string      `json:"priceType"`
			FormattedValue string      `json:"formattedValue"`
			MinQuantity    interface{} `json:"minQuantity"`
			MaxQuantity    interface{} `json:"maxQuantity"`
		} `json:"categoryPrice"`
		ValueForComparison int         `json:"valueForComparison"`
		UnitForComparison  string      `json:"unitForComparison"`
		UnitDescription    string      `json:"unitDescription"`
		DepositPrice       interface{} `json:"depositPrice"`
		Gallery360Images   interface{} `json:"gallery360Images"`
		Gallery360Link     interface{} `json:"gallery360Link"`
		GalleryAudios      interface{} `json:"galleryAudios"`
		GalleryPdfs        interface{} `json:"galleryPdfs"`
		GalleryVideos      interface{} `json:"galleryVideos"`
		Links              interface{} `json:"links"`
		Icon               struct {
			ImageType    interface{} `json:"imageType"`
			Format       interface{} `json:"format"`
			URL          string      `json:"url"`
			AltText      string      `json:"altText"`
			GalleryIndex interface{} `json:"galleryIndex"`
			Width        interface{} `json:"width"`
			Code         interface{} `json:"code"`
		} `json:"icon"`
		NumberContentUnits         interface{} `json:"numberContentUnits"`
		Unit                       interface{} `json:"unit"`
		DeliveryTime               interface{} `json:"deliveryTime"`
		CommercialCategoryGroup    interface{} `json:"commercialCategoryGroup"`
		CommercialCategorySubGroup interface{} `json:"commercialCategorySubGroup"`
		Promotions                 interface{} `json:"promotions"`
		ProductPriceGroup          interface{} `json:"productPriceGroup"`
		SecondLevelCategory        interface{} `json:"secondLevelCategory"`
		CartStatus                 struct {
			InCart          bool        `json:"inCart"`
			Qty             interface{} `json:"qty"`
			SellingMethod   interface{} `json:"sellingMethod"`
			Comment         interface{} `json:"comment"`
			CartEntryNumber interface{} `json:"cartEntryNumber"`
		} `json:"cartStatus"`
		PromotionsDisplay                  interface{}   `json:"promotionsDisplay"`
		PromotionMsg                       interface{}   `json:"promotionMsg"`
		PromotionCharacteristicsImg        interface{}   `json:"promotionCharacteristicsImg"`
		PromotionCodes                     []interface{} `json:"promotionCodes"`
		MainPromotionCode                  interface{}   `json:"mainPromotionCode"`
		PromotionCount                     interface{}   `json:"promotionCount"`
		PromotionCharacteristicDescription interface{}   `json:"promotionCharacteristicDescription"`
		AllCategoryCodes                   []string      `json:"allCategoryCodes"`
		EffectiveMinQuantity               interface{}   `json:"effectiveMinQuantity"`
		EffectivePrice                     interface{}   `json:"effectivePrice"`
		EffectivePricePerUnit              interface{}   `json:"effectivePricePerUnit"`
		Remarks                            interface{}   `json:"remarks"`
		WeightConversion                   interface{}   `json:"weightConversion"`
		BaseProductImageLarge              string        `json:"baseProductImageLarge"`
		BaseProductImageMedium             string        `json:"baseProductImageMedium"`
		BaseProductImageSmall              string        `json:"baseProductImageSmall"`
		BaseProductDescription             string        `json:"baseProductDescription"`
		CoordinationType                   interface{}   `json:"coordinationType"`
		Calories                           interface{}   `json:"calories"`
		Fats                               interface{}   `json:"fats"`
		Healthy                            interface{}   `json:"healthy"`
		Sodium                             interface{}   `json:"sodium"`
		Sugar                              interface{}   `json:"sugar"`
		WeightIncrement                    float64       `json:"weightIncrement"`
		MaxWeight                          interface{}   `json:"maxWeight"`
		MinWeight                          interface{}   `json:"minWeight"`
		HealthAttributes                   []interface{} `json:"healthAttributes"`
		HealthRecommendation               interface{}   `json:"healthRecommendation"`
	} `json:"results"`
	Pagination struct {
		PageSize             int    `json:"pageSize"`
		CurrentPage          int    `json:"currentPage"`
		Sort                 string `json:"sort"`
		NumberOfPages        int    `json:"numberOfPages"`
		TotalNumberOfResults int    `json:"totalNumberOfResults"`
	} `json:"pagination"`
}
